name: Update Gradle Wrapper

on:
  schedule:
    - cron: "58 6 * * WED"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1.0.20
        with:
          set-distribution-checksum: false
